# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: transfer.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'transfer.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0etransfer.proto\x12\x08transfer\"\x18\n\x05\x43hunk\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\x0c\"0\n\x0cUploadStatus\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"+\n\x0f\x44ownloadRequest\x12\x18\n\x10remote_file_path\x18\x01 \x01(\t2\x85\x01\n\x0c\x46ileTransfer\x12\x37\n\nUploadFile\x12\x0f.transfer.Chunk\x1a\x16.transfer.UploadStatus(\x01\x12<\n\x0c\x44ownloadFile\x12\x19.transfer.DownloadRequest\x1a\x0f.transfer.Chunk0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'transfer_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CHUNK']._serialized_start=28
  _globals['_CHUNK']._serialized_end=52
  _globals['_UPLOADSTATUS']._serialized_start=54
  _globals['_UPLOADSTATUS']._serialized_end=102
  _globals['_DOWNLOADREQUEST']._serialized_start=104
  _globals['_DOWNLOADREQUEST']._serialized_end=147
  _globals['_FILETRANSFER']._serialized_start=150
  _globals['_FILETRANSFER']._serialized_end=283
# @@protoc_insertion_point(module_scope)
